name: Continuous Integration
on: 
  push:
    branches:
     - master-slave
     - '[0-9]+.[0-9]+-dev'
  pull_request:
    branches:
     - master-slave
     - '[0-9]+.[0-9]+-dev'
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        include:
          - os: ubuntu-20.04
            os_short: linux
            compiler_cc: clang
            compiler_cxx: clang++
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os_short }}-${{ matrix.compiler_cc }}
    env:
      SDKS: '["l4d2"]'
      ARCH: x86
      DEPENDENCIES_FOLDER: dependencies
      DEPENDENCIES_ROOT: ${{ github.workspace }}/dependencies
      MYSQL_VERSION: '5.5'
      MMSOURCE_VERSION: '1.12'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          path: sourcemod

      - name: Cache dependencies
        uses: actions/cache@v3
        env:
          cache-name: hl2sdk-mysql-mmsource
        with:
          path: ${{ env.DEPENDENCIES_ROOT }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-mysql${{ env.MYSQL_VERSION }}-mmsource${{ env.MMSOURCE_VERSION }}-${{ join(fromJSON(env.SDKS), '') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-mysql${{ env.MYSQL_VERSION }}-mmsource${{ env.MMSOURCE_VERSION }}-
            ${{ runner.os }}-build-${{ env.cache-name }}-mysql${{ env.MYSQL_VERSION }}-

      # Setup Python for AMBuild
      - uses: actions/setup-python@v4
        name: Setup Python 3.8
        with:
          python-version: 3.8
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        shell: bash
        run: |
          mkdir -p ${{ env.DEPENDENCIES_FOLDER }}
          cd ${{ env.DEPENDENCIES_FOLDER }}

          # Satisfy checkout-deps requirement for a "sourcemod" folder.
          mkdir -p sourcemod
          ../sourcemod/tools/checkout-deps.sh -s ${{ join(fromJSON(env.SDKS)) }}

      - name: Install Linux dependencies
        if: startsWith(runner.os, 'Linux')
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            gcc-multilib g++-multilib libstdc++6 lib32stdc++6 \
            libc6-dev libc6-dev-i386 linux-libc-dev \
            linux-libc-dev:i386 lib32z1-dev ${{ matrix.compiler_cc }}

      - name: Setup ccache action
  # You may pin to the exact commit or the version.
  # uses: Chocobo1/setup-ccache-action@c1caac940f0719c5709586f4e48fb2cfea86086b
        uses: Chocobo1/setup-ccache-action@v1.3.6
    
      - name: Select clang compiler
        if: startsWith(runner.os, 'Linux')
        run: |
          echo "CC=${{ matrix.compiler_cc }} -Ofast -ffast-math -Wno-error -pipe -fno-plt -fopenmp-simd -fexceptions -ftree-vectorize -ftree-slp-vectorize -mpclmul -fno-trapping-math -march=skylake -mtune=skylake" >> $GITHUB_ENV
          echo "CXX=${{ matrix.compiler_cxx }} -Ofast -ffast-math -Wno-error -pipe -fno-plt -fopenmp-simd -fexceptions -ftree-vectorize -ftree-slp-vectorize -mpclmul -fno-trapping-math -march=skylake -mtune=skylake" >> $GITHUB_ENV
          ${{ matrix.compiler_cc }} --version
          ${{ matrix.compiler_cxx }} --version

      - name: Build
        working-directory: sourcemod
        run: |
          mkdir build
          cd build
          python ../configure.py --enable-optimize --sdks=${{ join(fromJSON(env.SDKS)) }} --targets=${{ env.ARCH }} --mms-path=${{ env.DEPENDENCIES_ROOT }}/mmsource-${{ env.MMSOURCE_VERSION }} --hl2sdk-root=${{ env.DEPENDENCIES_ROOT }} --mysql-path=${{ env.DEPENDENCIES_ROOT }}/mysql-${{ env.MYSQL_VERSION }} --mysql64-path=${{ env.DEPENDENCIES_ROOT }}/mysql-${{ env.MYSQL_VERSION }}-x86_64
          ambuild

      #- name: pack
      #  working-directory: /home/runner/work/sourcemod/sourcemod/sourcemod/build
      #  run: tar -cf pak.tar.zst package --zstd
      
      - name: Uploading package
        uses: actions/upload-artifact@v3
        with:
          name: sourcemod-sm1.12-${{ matrix.os_short }}
          path: /home/runner/work/sourcemod/sourcemod/sourcemod/build/package
          
     # - name: Uploading package
     #   uses: actions/upload-artifact@v3
     #   with:
     #     name: sourcemod-sm1.12-${{ matrix.os_short }}.tar.zst
     #     path: /home/runner/work/sourcemod/sourcemod/sourcemod/pak.tar.zst
          
    #  - name: Uploading package
    #    uses: actions/upload-artifact@v3
    #    with:
    #      name: sourcemod-sm1.12-${{ matrix.os_short }}-full
    #      path: /home/runner/work/sourcemod/sourcemod/sourcemod

